trigger:
  branches:
    include:
    - main
    - master
    - release/*
    - develop
    exclude:
    - feature/*

workspace:
  clean: all

pool:
  name: 'Indium Local Agent Pool'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectName: 'SDSFinder'
  contextName: 'SDSFinderContext'

steps:
- checkout: self
  fetchDepth: 0
  
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'
    preferLatestVersion: true

- task: gitversion/execute@0
  displayName: Determine Version


- task: NuGetToolInstaller@1

- task: NuGetAuthenticate@1
  displayName: 'Authenticate NuGet Feeds'

- task: NuGetCommand@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    restoreSolution: '$(Solution)'
    feedsToUse: 'config'
    nugetConfigPath: '$(Build.SourcesDirectory)/nuget.config' 

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(BuildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(BuildConfiguration)'
  inputs:
    command: 'test'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish $(BuildConfiguration)'
  inputs:
    command: 'publish'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/out --no-self-contained'
  
- task: DotNetCoreCLI@2
  displayName: 'dotnet ef migrations bundle'
  inputs:
    command: 'custom'
    custom: 'ef'
    arguments: 'migrations bundle -c $(contextName) --configuration bundle --force --startup-project $(projectName)\$(projectName).csproj --project $(projectName)\$(projectName).csproj --output $(Build.ArtifactStagingDirectory)/out/efbundle.exe --verbose'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/out'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(projectName)-$(Build.BuildId).zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)/$(projectName)-$(Build.BuildId).zip
    ArtifactName: $(projectName)

